"""add iscancel field

Revision ID: 3ee56c9f1185
Revises: e468b22e07ce
Create Date: 2025-07-18 21:29:18.082385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ee56c9f1185'
down_revision: Union[str, Sequence[str], None] = 'e468b22e07ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('iscancel', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record', 'iscancel')
    # ### end Alembic commands ###
